rabbitmq:
  config:
    hostname: albatross.rmq.cloudamqp.com
    password: YMwtr1XrP6H3JBCryMGlN-_ge-raXkTd
    username: yfyxkhgq
    virtualHost: yfyxkhgq
    queueName: florian935.queue
    exchangeName: florian935.exchange
    routingKey: florian935.routingKey