server:
  port: 8081
rabbitmq:
  config:
    hostname: YOUR_HOSTNAME
    password: YOUR_PASSWORD
    username: YOUR_USERNAME
    virtualHost: YOUR_VIRTUAL_HOST
    queueName: florian935.queue
    exchangeName: florian935.exchange
    routingKey: florian935.routingKey
